[colors.primary]
background = '#101418'
foreground = '#e0e2e8'

[colors.selection]
text = '#e0e2e8'
background = '#0d47a1'

[colors.cursor]
text = '#101418'
cursor = '#42a5f5'

[colors.normal]
black   = '#101418'
red     = '#ff3270'
green   = '#42f558'
yellow  = '#fff332'
blue    = '#1c8de8'
magenta = '#003e71'
cyan    = '#42a5f5'
white   = '#e8f4ff'

[colors.bright]
black   = '#8d979f'
red     = '#ff739e'
green   = '#7cff8d'
yellow  = '#fff77c'
blue    = '#60b8ff'
magenta = '#7cc4ff'
cyan    = '#abd9ff'
white   = '#f5faff'
